#!/usr/bin/with-contenv bash

## Ubuntu
if [ -f /usr/bin/apt ]; then
    echo "\
        curl \
        wget \
        jq" >> /mod-repo-packages-to-install.list
        # iptables" >> /mod-repo-packages-to-install.list

fi
# Alpine
if [ -f /sbin/apk ]; then
    echo "\
        curl \
        wget \
        jq" >> /mod-repo-packages-to-install.list
        # iptables" >> /mod-repo-packages-to-install.list
fi

echo "TAILSCALE_USE_IPTABLES: $TAILSCALE_USE_IPTABLES"
enable_flag=${TAILSCALE_USE_IPTABLES}
# convert int to str
if [ "${enable_flag}" -eq 1 ] 2>/dev/null; then
    enable_flag="true"
elif [ "${enable_flag}" -eq 0 ] 2>/dev/null; then
    enable_flag="false"
fi

# Convert enable_flag to lowercase for comparison
enable_flag_lower=$(echo "${enable_flag}" | tr '[:upper:]' '[:lower:]')

# perform the actual check
if [ "${enable_flag_lower}" == "true" ]; then
    echo "enabling IPTables installation"
    echo "iptables" >> /mod-repo-packages-to-install.list
else
    echo "disabling IPTables installation"
fi