#!/usr/bin/with-contenv bash

## Ubuntu
if [ -f /usr/bin/apt ]; then
    echo "\
        curl \
        wget \
        jq" >> /mod-repo-packages-to-install.list
        # iptables" >> /mod-repo-packages-to-install.list

fi
# Alpine
if [ -f /sbin/apk ]; then
    echo "\
        curl \
        wget \
        jq" >> /mod-repo-packages-to-install.list
        # iptables" >> /mod-repo-packages-to-install.list
fi

echo "TAILSCALE_USE_IPTABLES: $TAILSCALE_USE_IPTABLES"
if [ -v TAILSCALE_USE_IPTABLES ]; then
    echo "enabling IPTables installation"
    echo "iptables" >> /mod-repo-packages-to-install.list
fi